apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: LoadBalancer  #loadbalancer to make our app accessible fome internet with public ip,  Or ClusterIP for internal access, NodePort for node access
  selector:
    app: myapp
  ports:
  - protocol: TCP
    port: 80  # External port
    targetPort: 3000  # Container port