name: CI Pipeline
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest #runs on ubuntu machine runner
    steps:
      - uses: actions/checkout@v4 #checkout/copy code from repo to runner
      - uses: actions/setup-node@v4 #setup node environment on runner
        with:
          node-version: '18' #specify node version, it will install this version on runner
      - run: npm install
      - run: npm run lint

  build:
    needs: lint #runs only if lint passes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install
      - run: npm test

  deploy:
    needs: build  #runs only if build passes
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' #only runs on main branch
    steps:
      - uses: actions/checkout@v4
      - run: echo "Deploying to Kubernetes..."
      - run: kubectl apply -f k8s/